config/routes.rb
Rails.application.routes.draw do
  resources :customer_contacts
  root 'landings#index'
  get 'dashboard', :to => 'pages#index'

  devise_for :users, :controllers => { :registrations => "user/registrations", sessions: 'user/sessions' }
  resources :users

  namespace :api do
    # API Module
    namespace :v1 do
      # Version 1
      get 'events', to: 'event_slots#index'
    end

  end

  get '/products/search', to: 'products#search'

  resources :teams, :except => [:index] do

    resources :invites

    member do
      get :dashboard
      get :completed_orders
    end

    resources :event_slots

    resources :memberships do
      member do
        post :approve
        post :decline
        post :promote
      end
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    get 'leads', to: 'dashboard#leads'
    get 'pending-scheduling', to: 'dashboard#pending_scheduling'
    get 'scheduled', to: 'dashboard#scheduled'

    resources :armor_types
    resources :categories
    resources :classifications
    resources :characters
    resources :customers do
      resources :customer_contacts, as: 'contacts', path: 'contacts', :only => [:new, :create, :edit, :update, :destroy]
    end
    resources :difficulties
    resources :event_slots
    resources :factions
    resources :loot_options
    resources :memberships
    resources :mounts
    resources :order_line_statuses
    resources :payment_statuses
    resources :payment_types
    resources :play_styles
    resources :primary_stats
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :regions
    resources :team_statuses
    resources :teams
    resources :tier_tokens
    resources :users
    resources :zones

    resources :order_lines, except: [:index] do

      collection do
        get :completed
      end

      member do
        get 'complete'
        get 'send_confirmation'
      end
    end
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates :user, uniqueness: {scope: :team}

  belongs_to :user
  belongs_to :team

  validates :user, :team, presence: true

  scope :by_user, -> (user) { where(user: user) }
  scope :by_team, -> (team) { where(team: team) }
  scope :confirmed, -> { where confirmed: true }
  scope :unconfirmed, -> { where confirmed: false }

  scope :owner, -> { where owner: true }

  def approve!
    self.update(confirmed: true, owner: false)
  end

  def decline!
    self.destroy
  end

  def promote!
    Membership.where(:team_id => self.team).update_all(:owner => false)
    self.update(confirmed: true, owner: true)
  end

  def owner?
    self.owner
  end

  def confirmed?
    self.confirmed
  end

  def status
    if owner? && confirmed?
      :owner
    elsif !owner? && confirmed?
      :member
    elsif !owner? && !confirmed?
      :pending
    else
      :unprocessable
    end
  end

end

app/controllers/admin/memberships_controller.rb
class Admin::MembershipsController < AdminController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  def index
    @memberships = ::Membership.all
  end

  def show
  end

  def new
    @membership = ::Membership.new
  end

  def edit
  end

  def create
    @membership = ::Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to admin_membership_path(@membership), notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to admin_membership_path(@membership), notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to admin_memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_membership
      @membership = ::Membership.find(params[:id])
    end

    def membership_params
      params.require(:membership).permit(:user_id, :team_id, :confirmed, :owner)
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  load_and_authorize_resource
  before_action :set_membership, except: :index
  before_action :set_team, only: [:index]

  def index
    @memberships = @team.memberships.includes(:user).all.order(owner: :desc, confirmed: :desc)
  end

  def approve
    @membership.approve!
    redirect_to team_memberships_path(@membership.team), {team_id: @membership.team.id}
  end

  def decline
    @membership.destroy
    redirect_to team_memberships_path(@membership.team), {team_id: @membership.team.id}
  end

  def promote
    @membership.promote!
    redirect_to team_memberships_path(@membership.team), {team_id: @membership.team.id}
  end

  private
  def set_membership
    @membership = Membership.find(params[:id])
  end
  def set_team
    @team = Team.find(params[:team_id])
  end

  def membership_params
    params.require(:membership).permit(:user_id, :team_id, :confirmed, :owner)
  end
end

app/views/memberships/_approve_button.html.erb
<%= simple_form_for(approve_button, remote: true, html: {style: "display:inline;"}) do |f| %>
		<%= f.hidden_field :id, :value => approve_button.id %>
		<%= f.hidden_field :confirmed, :value => true %>
		<%= f.submit "Approve", class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/memberships/_form.html.erb
<%= simple_form_for([@team, @membership]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :team %>
    <%= f.input :confirmed %>
    <%= f.input :owner %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div class="row">
  <div class="col-md-1"><%= membership.status.to_s.titleize %></div>
  <div class="col-md-3"><%= membership.user.display_name %></div>
  <div class="col-md-4"><%= membership.user.email %></div>
  <div class="col-md-4">
    <% if can? :update, membership %>

    <% if membership.confirmed? %>

    <% unless membership.owner? %>

    <%= link_to promote_team_membership_path(membership.team, membership),
    method: :post,
    remote: true,
    data: {confim: 'Are you sure?'},
    class: 'btn btn-primary btn-xs' do %>
    <i class="fa fa-trophy"></i>
    <% end %>

    <%= link_to decline_team_membership_path(membership.team, membership),
    method: :post,
    remote: true,
    data: {confim: 'Are you sure?'},
    class: 'btn btn-danger btn-xs' do %>
    <i class="fa fa-ban"></i>
    <% end %>

    <% end %>

    <% else %>

    <%= link_to approve_team_membership_path(membership.team, membership),
    method: :post,
    remote: true,
    data: {confim: 'Are you sure?'},
    class: 'btn btn-success btn-xs' do %>
    <i class="fa fa-check"></i>
    <% end %>

    <%= link_to decline_team_membership_path(membership.team, membership),
    method: :post,
    remote: true,
    data: {confim: 'Are you sure?'},
    class: 'btn btn-danger btn-xs' do %>
    <i class="fa fa-ban"></i>
    <% end %>

    <% end %>

    <% end %>
  </div>
</div>

app/views/memberships/_promote_button.html.erb
<%= simple_form_for(promote_button, remote: true, html: {style: "display:inline;"}) do |f| %>
		<%= f.hidden_field :id, :value => promote_button.id %>
		<%= f.hidden_field :owner, :value => true %>
		<%= f.submit "Promote", class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/memberships/_remove_button.html.erb
<%= simple_form_for(remove_button, remote: true, html: {style: "display:inline;"}) do |f| %>
		<%= f.hidden_field :id, :value => remove_button.id %>
		<%= f.hidden_field :confirmed, :value => false %>
		<%= f.submit "Remove", class: 'btn btn-default btn-sm' %>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', team_membership_path(@team, @membership) %> |
<%= link_to 'Back', team_memberships_path(@team) %>

app/views/memberships/index.js.erb
$('#memberships').html("<%= j (render partial: @memberships) %>");

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

app/views/memberships/show.html.erb
<p>
  <strong>User:</strong>
  <%= @membership.user.display_name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @membership.team.display_name %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @membership.confirmed %>
</p>

<%= link_to 'Edit', edit_team_membership_path(@team, @membership) %> |
<%= link_to 'Back', team_memberships_path(@team) %>

app/views/memberships/update.js.erb
$('#memberships').html("<%= j (render partial: @memberships) %>");