config/routes.rb
Rails.application.routes.draw do
  resources :customer_contacts
  root 'landings#index'
  get 'dashboard', :to => 'pages#index'

  devise_for :users, :controllers => { :registrations => "user/registrations", sessions: 'user/sessions' }
  resources :users

  namespace :api do
    # API Module
    namespace :v1 do
      # Version 1
      get 'events', to: 'event_slots#index'
    end

  end

  get '/products/search', to: 'products#search'

  resources :teams, :except => [:index] do

    resources :invites

    member do
      get :dashboard
      get :completed_orders
    end

    resources :event_slots

    resources :memberships do
      member do
        post :approve
        post :decline
        post :promote
      end
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    get 'leads', to: 'dashboard#leads'
    get 'pending-scheduling', to: 'dashboard#pending_scheduling'
    get 'scheduled', to: 'dashboard#scheduled'

    resources :armor_types
    resources :categories
    resources :classifications
    resources :characters
    resources :customers do
      resources :customer_contacts, as: 'contacts', path: 'contacts', :only => [:new, :create, :edit, :update, :destroy]
    end
    resources :difficulties
    resources :event_slots
    resources :factions
    resources :loot_options
    resources :memberships
    resources :mounts
    resources :order_line_statuses
    resources :payment_statuses
    resources :payment_types
    resources :play_styles
    resources :primary_stats
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :regions
    resources :team_statuses
    resources :teams
    resources :tier_tokens
    resources :users
    resources :zones

    resources :order_lines, except: [:index] do

      collection do
        get :completed
      end

      member do
        get 'complete'
        get 'send_confirmation'
      end
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :order_lines
  has_many :characters, through: :order_lines
  has_many :customer_contacts, dependent: :destroy

  validates  :email, presence: true, uniqueness: true

  require 'json'

  def to_label
    self.email
  end

  def self.importJSON(file)
    json = parseJSON file
    customers = json['customers']

    customers.each do |row|
      row['email'].downcase!
      row['battle_tag'].downcase!
      row['skype'].downcase!
      Customer.find_or_create_by(email: row['email']) do |customer|
        customer.battle_tag = row['battle_tag']
        customer.skype = row['skype']
      end
    end
  end

  def self.parseJSON(f)
    ActiveSupport::JSON.decode( File.read( f.path ) )
  end

  def first_battle_tag
    customer_contacts.where(ctype: 'battle_tag').first
  end

  def first_skype
    customer_contacts.where(ctype: 'skype').first
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminController
  before_action :set_customer, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_order_totals, only: [:index, :show]
  before_action :set_recent_orders, only: [:index, :show]

  # GET /Customers
  # GET /Customers.json
  def index
    @customers = Customer.all.order(email: :asc)

    @skype_contacts = CustomerContact.joins(:customer).where(ctype: 'skype')
  end

  # GET /Customers/1
  # GET /Customers/1.json
  def show
  end

  # GET /Customers/new
  def new
    @customer = Customer.new
  end

  # GET /Customers/1/edit
  def edit
  end

  # POST /Customers
  # POST /Customers.json
  def create
    @customer = ::Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to admin_customer_path(@customer), notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Customers/1
  # PATCH/PUT /Customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to admin_customer_path(@customer), notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Customers/1
  # DELETE /Customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      if params[:id]
        @customer = Customer.find(params[:id])
      else
        @customer = Customer.first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:email, :battle_tag, :skype)
    end

   def set_recent_orders
      @completed_orders = @customer
        .order_lines
        .where_completed
        .completed_at_desc
   end

    def set_order_totals
      @customers_completed_orders = @customer.order_lines.where_completed
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def skype_link(skype)
    link_to(skype, "skype:#{skype}?chat")
  end
end

app/views/admin/customers/_customer.html.erb
<tr>
  <td><%= link_to customer.email, admin_customer_path(customer) %></td>
</tr>

app/views/admin/customers/_form.html.erb
		<%= simple_form_for([:admin, @customer]) do |f| %>
		    <div class="form-inputs">
		    <%= f.input :email %>

		  </div>
			<div class="btn-group">
				<%= f.button :submit, :class => "btn btn-primary btn-sm" %>
				<%= yield :buttons %>
			</div>
		<% end %>

app/views/admin/customers/_skype.html.erb
<tr>
  <td><%= skype.value %></td>
  <td><%= skype.customer.email %></td>
  <td><%= link_to 'View', [:admin, skype.customer] %></td>
</tr>

app/views/admin/customers/edit.html.erb
<% content_for :buttons do %>
	<%= link_to 'Back', admin_customers_path, :class => "btn btn-default btn-sm" %>
	<%= link_to 'Show', admin_customer_path(@customer), :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Edit Armor Type</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<br />

app/views/admin/customers/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="block-flat">
      <h3>Customers</h3>
      <table class="no-border datatable">
        <thead class="no-border">
          <th>Email Address</th>
        </thead>
        <tbody class="no-border-y">
          <% if @customers.count > 0 %>
          <%= render @customers %>
          <% else %>
          <tr>
            <td colspan="5" class="text-center">There are no customers.</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <div class="block-flat">
      <h3>Skype Contacts</h3>
      <table class="no-border" id="skype_contacts_table">
        <thead class="no-border">
          <th>Address</th>
          <th>Owner</th>
          <th></th>
        </thead>
        <tbody class="no-border-y">
          <% if @skype_contacts.count > 0 %>
          <%= render partial: 'admin/customers/skype', collection: @skype_contacts %>
          <% else %>
          <tr>
            <td colspan="5" class="text-center">There are no skype contacts.</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% content_for :foot_js do %>
    $('#skype_contacts_table').dataTable({
        "pageLength": 15,
        "lengthChange": false,
        "columnDefs": [ {
          "targets": 1,
          "searchable": false
        } ]
  });
<% end %>

app/views/admin/customers/new.html.erb
<% content_for :buttons do %>
<%= link_to 'Back', admin_customers_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Create Customer</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	</div>
</div>
<br />

app/views/admin/customers/show.html.erb
<div class="row">

	<div class="col-md-4">
		<div class="block-flat">
			<h3>Contacts</h3>
			<table class="no-border">
				<tbody class="no-border-x">
					<tr>
						<th>Email (Primary)</th>
						<td><%= @customer.email %></td>
					</tr>
					<% @customer.customer_contacts.each do |contact| %>
					<tr>
						<th><%= contact.display_type %></th>
						<td><%= contact.value %></td>
						<td>
							<%= link_to admin_customer_contact_path(@customer, contact), method: :delete, data: { confirm: 'Are you sure?' } do %>
							<i class="fa fa-trash"></i>
							<% end %>
							</td>
					</tr>
					<% end %>
					<tr>
						<td colspan="3">
							<%= link_to 'New', new_admin_customer_contact_path(@customer) %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<% if @completed_orders.any? %>
	<div class="col-md-4">
		<div class="block-flat">
			<h3>Summary</h3>
			<table class="no-border">
				<tbody class="no-border-x">
					<tr>
						<th># Sales</th>
						<td><%= @customers_completed_orders.count(:sale) %></td>
					</tr>
					<tr>
						<th>Avg. Sale</th>
						<td><%= number_to_currency @customers_completed_orders.average(:sale) %></td>
					</tr>
					<tr>
						<th>Total Sales</th>
						<td><%= number_to_currency @customers_completed_orders.sum(:sale) %> </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-md-4">
		<div class="block-flat">
			<h3>Team History</h3>
			<table class="no-border">
				<thead class="no-border">
					<tr>
						<th>Team</th>
						<th>#</th>
						<th>Total $</th>
					</tr>
				</thead>
				<tbody class="no-border-y">
					<% @customers_completed_orders.group_by(&:team).each do |team, orders| %>
					<tr>
						<td><%= team.display_name %></td>
						<td><%= orders.count %></td>
						<td><%= number_to_currency orders.sum(&:contractor_payment) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <h3>Order History</h3>
      <table class="no-border" id="admin-customers-order-history">
        <thead class="no-border">
          <tr>
            <th>#</th>
            <th>Date</th>
            <th>Character</th>
            <th>Category</th>
            <th>Difficulty</th>
            <th>Zone</th>
            <th>Description</th>
            <th>Mount</th>
            <th>Sale</th>
          </tr>
        </thead>
        <tbody class="no-border-y">
          <% @completed_orders.each do |order_line| %>
          <tr>
            <td><%= link_to "##{order_line.order}", admin_order_line_path(order_line) %></td>
            <td><%= order_line.completed_at.to_s(:order_line) %></td>
            <td>
              <%= faction_sprite(order_line.faction) %>
              <%= character_sprite(order_line.character) %>
            </td>
            <td><%= order_line.product.category.display_name %></td>
            <td><%= order_line.product.difficulty.display_name %></td>
            <td><%= order_line.product.zone.display_name %></td>
            <td><%= order_line.product.display_name %></td>
            <td><%= order_line.product.mount.display_name %></td>
            <td style="text-align:right;"><%= number_to_currency order_line.sale %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% end %>
<div class="col-md-12">
	<div class="btn-group">
		<%= link_to "Edit", edit_admin_customer_path(@customer), class: 'btn btn-primary' %>
	</div>
</div>
<% content_for :foot_js do %>
$('#admin-customers-order-history').dataTable({
    "pageLength": 5,
    "lengthChange": false,
    "order": [[ 1, 'desc' ]],
    "columnDefs": [
    { "orderable": false, "targets": 2 }
  ]
});
<% end %>