config/routes.rb
Rails.application.routes.draw do
  resources :customer_contacts
  root 'landings#index'
  get 'dashboard', :to => 'pages#index'

  devise_for :users, :controllers => { :registrations => "user/registrations", sessions: 'user/sessions' }
  resources :users

  namespace :api do
    # API Module
    namespace :v1 do
      # Version 1
      get 'events', to: 'event_slots#index'
    end

  end

  get '/products/search', to: 'products#search'

  resources :teams, :except => [:index] do

    resources :invites

    member do
      get :dashboard
      get :completed_orders
    end

    resources :event_slots

    resources :memberships do
      member do
        post :approve
        post :decline
        post :promote
      end
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    get 'leads', to: 'dashboard#leads'
    get 'pending-scheduling', to: 'dashboard#pending_scheduling'
    get 'scheduled', to: 'dashboard#scheduled'

    resources :armor_types
    resources :categories
    resources :classifications
    resources :characters
    resources :customers do
      resources :customer_contacts, as: 'contacts', path: 'contacts', :only => [:new, :create, :edit, :update, :destroy]
    end
    resources :difficulties
    resources :event_slots
    resources :factions
    resources :loot_options
    resources :memberships
    resources :mounts
    resources :order_line_statuses
    resources :payment_statuses
    resources :payment_types
    resources :play_styles
    resources :primary_stats
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :regions
    resources :team_statuses
    resources :teams
    resources :tier_tokens
    resources :users
    resources :zones

    resources :order_lines, except: [:index] do

      collection do
        get :completed
      end

      member do
        get 'complete'
        get 'send_confirmation'
      end
    end
  end

end

app/models/primary_stat.rb
class PrimaryStat < ActiveRecord::Base
	before_save :downcase_fields
	include OptionMethods

	validates_presence_of  :name, message: "of primary stat must not be blank."
	validates_uniqueness_of :name, message: "%{value} already exists."

  # Scopes
  scope :by_name,->(v) { find_by name: v }

	def downcase_fields
		self.name.downcase
	end

	default_scope { order(name: :asc) }
end

app/controllers/admin/primary_stats_controller.rb
class Admin::PrimaryStatsController < AdminController
  before_action :set_primary_stat, only: [:show, :edit, :update, :destroy]

  def index
    @primary_stats = ::PrimaryStat.all
  end

  def show
  end

  def new
    @primary_stat = ::PrimaryStat.new
  end

  def edit
  end

  def create
    @primary_stat = ::PrimaryStat.new(primary_stat_params)

    respond_to do |format|
      if @primary_stat.save
        format.html { redirect_to admin_primary_stat_path(@primary_stat), notice: 'Primary stat was successfully created.' }
        format.json { render :show, status: :created, location: @primary_stat }
      else
        format.html { render :new }
        format.json { render json: @primary_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @primary_stat.update(primary_stat_params)
        format.html { redirect_to admin_primary_statspath(@primary_stat), notice: 'Primary stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @primary_stat }
      else
        format.html { render :edit }
        format.json { render json: @primary_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @primary_stat.destroy
    respond_to do |format|
      format.html { redirect_to admin_primary_stats_url, notice: 'Primary stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_primary_stat
      @primary_stat = ::PrimaryStat.find(params[:id])
    end

    def primary_stat_params
      params.require(:primary_stat).permit(:name)
    end
end

app/views/admin/primary_stats/_form.html.erb
		<%= simple_form_for([:admin, @primary_stat]) do |f| %>
		    <div class="form-inputs">
		    <%= f.input :name %>
		  </div>
			<div class="btn-group">
				<%= f.button :submit, :class => "btn btn-primary btn-sm" %>
				<%= yield :buttons %>
			</div>
		<% end %>		

app/views/admin/primary_stats/_primary_stat.html.erb
      <tr>
        <td><%= primary_stat.display_name %></td>
        <td><%= link_to 'Edit', edit_admin_primary_stat_path(primary_stat) %></td>
        <td><%= link_to 'Destroy', admin_primary_stat_path(primary_stat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr
      

app/views/admin/primary_stats/edit.html.erb
<% content_for :buttons do %>
	<%= link_to 'Back', admin_primary_stats_path, :class => "btn btn-default btn-sm" %>
	<%= link_to 'Show', admin_primary_stat_path(@primary_stat), :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Edit Primary Stat</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<br />

app/views/admin/primary_stats/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Primary Stats</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= link_to '<i class="fa fa-plus"></i> New'.html_safe, new_admin_primary_stat_path, :class => 'btn btn-primary btn-sm pull-right' %>    
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'primary_stat', collection: @primary_stats %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/primary_stats/new.html.erb
<% content_for :buttons do %>
<%= link_to 'Back', admin_primary_stats_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Create Primary Stat</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	</div>
</div>
<br />

app/views/admin/primary_stats/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @primary_stat.name %>
</p>

<%= link_to 'Edit', edit_admin_primary_stat_path(@primary_stat) %> |
<%= link_to 'Back', admin_primary_stats_path %>