config/routes.rb
Rails.application.routes.draw do
  resources :customer_contacts
  root 'landings#index'
  get 'dashboard', :to => 'pages#index'

  devise_for :users, :controllers => { :registrations => "user/registrations", sessions: 'user/sessions' }
  resources :users

  namespace :api do
    # API Module
    namespace :v1 do
      # Version 1
      get 'events', to: 'event_slots#index'
    end

  end

  get '/products/search', to: 'products#search'

  resources :teams, :except => [:index] do

    resources :invites

    member do
      get :dashboard
      get :completed_orders
    end

    resources :event_slots

    resources :memberships do
      member do
        post :approve
        post :decline
        post :promote
      end
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    get 'leads', to: 'dashboard#leads'
    get 'pending-scheduling', to: 'dashboard#pending_scheduling'
    get 'scheduled', to: 'dashboard#scheduled'

    resources :armor_types
    resources :categories
    resources :classifications
    resources :characters
    resources :customers do
      resources :customer_contacts, as: 'contacts', path: 'contacts', :only => [:new, :create, :edit, :update, :destroy]
    end
    resources :difficulties
    resources :event_slots
    resources :factions
    resources :loot_options
    resources :memberships
    resources :mounts
    resources :order_line_statuses
    resources :payment_statuses
    resources :payment_types
    resources :play_styles
    resources :primary_stats
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :regions
    resources :team_statuses
    resources :teams
    resources :tier_tokens
    resources :users
    resources :zones

    resources :order_lines, except: [:index] do

      collection do
        get :completed
      end

      member do
        get 'complete'
        get 'send_confirmation'
      end
    end
  end

end

app/models/loot_option.rb
class LootOption < ActiveRecord::Base
	before_save :downcase_fields
	include OptionMethods

	validates_presence_of  :name, message: "of loot option must not be blank."
	validates_uniqueness_of :name, message: "%{value} already exists."

  # Scopes
  scope :by_name,->(v) { where name: v }

	def downcase_fields
		self.name.downcase
	end

	default_scope { order(name: :asc) }
end

app/controllers/admin/loot_options_controller.rb
class Admin::LootOptionsController < AdminController
  before_action :set_loot_option, only: [:show, :edit, :update, :destroy]

  def index
    @loot_options = ::LootOption.all
  end

  def show
  end

  def new
    @loot_option = ::LootOption.new
  end

  def edit
  end

  def create
    @loot_option = ::LootOption.new(loot_option_params)

    respond_to do |format|
      if @loot_option.save
        format.html { redirect_to admin_loot_option_path(@loot_option), notice: 'Loot option was successfully created.' }
        format.json { render :show, status: :created, location: @loot_option }
      else
        format.html { render :new }
        format.json { render json: @loot_option.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @loot_option.update(loot_option_params)
        format.html { redirect_to admin_loot_option_path(@loot_option), notice: 'Loot option was successfully updated.' }
        format.json { render :show, status: :ok, location: @loot_option }
      else
        format.html { render :edit }
        format.json { render json: @loot_option.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @loot_option.destroy
    respond_to do |format|
      format.html { redirect_to admin_loot_options_url, notice: 'Loot option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_loot_option
      @loot_option = ::LootOption.find(params[:id])
    end

    def loot_option_params
      params.require(:loot_option).permit(:name)
    end
end

app/views/admin/loot_options/_faction.html.erb
      <tr>
        <td><%= loot_option.display_name %></td>
        <td><%= link_to 'Edit', edit_admin_loot_option_path(loot_option) %></td>
        <td><%= link_to 'Destroy', admin_loot_option_path(loot_option), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr
      

app/views/admin/loot_options/_form.html.erb
		<%= simple_form_for([:admin, @loot_option]) do |f| %>
		    <div class="form-inputs">
		    <%= f.input :name %>
		  </div>
			<div class="btn-group">
				<%= f.button :submit, :class => "btn btn-primary btn-sm" %>
				<%= yield :buttons %>
			</div>
		<% end %>		

app/views/admin/loot_options/_loot_option.html.erb
      <tr>
        <td><%= loot_option.display_name %></td>
        <td><%= link_to 'Edit', edit_admin_loot_option_path(loot_option) %></td>
        <td><%= link_to 'Destroy', admin_loot_option_path(loot_option), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr
      

app/views/admin/loot_options/edit.html.erb
<% content_for :buttons do %>
	<%= link_to 'Back', admin_loot_options_path, :class => "btn btn-default btn-sm" %>
	<%= link_to 'Show', admin_loot_option_path(@loot_option), :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Edit Loot Option</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<br />

app/views/admin/loot_options/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Loot Options</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= link_to '<i class="fa fa-plus"></i> New'.html_safe, new_admin_loot_option_path, :class => 'btn btn-primary btn-sm pull-right' %>    
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'loot_option', collection: @loot_options %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/loot_options/new.html.erb
<% content_for :buttons do %>
<%= link_to 'Back', admin_loot_options_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<h3>Create Loot Option</h3>  
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	</div>
</div>
<br />

app/views/admin/loot_options/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @loot_option.name %>
</p>

<%= link_to 'Edit', edit_admin_loot_option_path(@loot_option) %> |
<%= link_to 'Back', admin_loot_options_path %>